GET http://localhost:3001/api/persons

###
GET http://localhost:3001/wrongroute

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/685bfbbfa81b2b2efc82709a

###
GET http://localhost:3001/api/persons/685d954fcca262296fbe6d67

###
GET http://localhost:3001/api/persons/30

###
DELETE http://localhost:3001/api/persons/685d954fcca262296fbe6d67

###
DELETE http://localhost:3001/api/persons/wrongid

###
PUT http://localhost:3001/api/persons/685d954fcca262296fbe6d67

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Veronique Bondieu",
    "number": "57-86-5847653"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Dominique Prout",
    "birthday": "1992-07-28"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "34-56-9875634",
    "birthday": "1992-07-28"
}